cmake_minimum_required(VERSION 3.14)
project(auto-win-msvc VERSION 0.1.0 LANGUAGES C)
add_subdirectory(posix-types)
add_subdirectory(posix-core)
add_subdirectory(posix-stat)
add_subdirectory(posix-dirent)
add_subdirectory(posix-dlfcn)
add_subdirectory(posix-mman)
add_subdirectory(posix-pthread)
add_subdirectory(posix-sockets)
add_subdirectory(posix-syslog)
add_subdirectory(posix-termios)
add_subdirectory(posix-glob)
add_subdirectory(posix-ipc)
add_subdirectory(posix-pwdgrp)
add_subdirectory(posix-utsname)
add_subdirectory(posix-libgen)
add_subdirectory(posix-spawn)
add_subdirectory(posix-wait)
add_subdirectory(posix-time)
