cmake_minimum_required(VERSION 3.14)

project(linux-sys-timerfd LANGUAGES C)

file(GLOB SOURCES "src/*.c")
if(SOURCES)
    add_library(linux-sys-timerfd STATIC ${SOURCES})
    target_include_directories(linux-sys-timerfd PUBLIC "include")
    target_link_libraries(linux-sys-timerfd PUBLIC posix-time)
else()
    add_library(linux-sys-timerfd INTERFACE)
    target_include_directories(linux-sys-timerfd INTERFACE "include")
endif()

if(NOT TARGET greatest)
    include(FetchContent)
    FetchContent_Declare(greatest SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../greatest")
    FetchContent_MakeAvailable(greatest)
endif()
if(NOT TARGET posix-time)
    add_subdirectory("../posix-time" "${CMAKE_CURRENT_BINARY_DIR}/posix-time")
endif()
enable_testing()
file(GLOB TEST_SOURCES "tests/*.c")
add_executable(test_linux-sys-timerfd ${TEST_SOURCES})
if(TARGET linux-sys-timerfd)
    target_link_libraries(test_linux-sys-timerfd PRIVATE linux-sys-timerfd greatest posix-time)
else()
    target_link_libraries(test_linux-sys-timerfd PRIVATE greatest posix-time)
endif()
add_test(NAME test_linux-sys-timerfd COMMAND test_linux-sys-timerfd)
