sigs = {
    "pthread_atfork": "int pthread_atfork(void (*prepare)(void), void (*parent)(void), void (*child)(void));",
    "pthread_attr_destroy": "int pthread_attr_destroy(pthread_attr_t *attr);",
    "pthread_attr_getdetachstate": "int pthread_attr_getdetachstate(const pthread_attr_t *attr, int *detachstate);",
    "pthread_attr_getguardsize": "int pthread_attr_getguardsize(const pthread_attr_t *attr, size_t *guardsize);",
    "pthread_attr_getinheritsched": "int pthread_attr_getinheritsched(const pthread_attr_t *attr, int *inheritsched);",
    "pthread_attr_getschedparam": "int pthread_attr_getschedparam(const pthread_attr_t *attr, struct sched_param *param);",
    "pthread_attr_getschedpolicy": "int pthread_attr_getschedpolicy(const pthread_attr_t *attr, int *policy);",
    "pthread_attr_getscope": "int pthread_attr_getscope(const pthread_attr_t *attr, int *contentionscope);",
    "pthread_attr_getstack": "int pthread_attr_getstack(const pthread_attr_t *attr, void **stackaddr, size_t *stacksize);",
    "pthread_attr_getstacksize": "int pthread_attr_getstacksize(const pthread_attr_t *attr, size_t *stacksize);",
    "pthread_attr_init": "int pthread_attr_init(pthread_attr_t *attr);",
    "pthread_attr_setdetachstate": "int pthread_attr_setdetachstate(pthread_attr_t *attr, int detachstate);",
    "pthread_attr_setguardsize": "int pthread_attr_setguardsize(pthread_attr_t *attr, size_t guardsize);",
    "pthread_attr_setinheritsched": "int pthread_attr_setinheritsched(pthread_attr_t *attr, int inheritsched);",
    "pthread_attr_setschedparam": "int pthread_attr_setschedparam(pthread_attr_t *attr, const struct sched_param *param);",
    "pthread_attr_setschedpolicy": "int pthread_attr_setschedpolicy(pthread_attr_t *attr, int policy);",
    "pthread_attr_setscope": "int pthread_attr_setscope(pthread_attr_t *attr, int contentionscope);",
    "pthread_attr_setstack": "int pthread_attr_setstack(pthread_attr_t *attr, void *stackaddr, size_t stacksize);",
    "pthread_attr_setstacksize": "int pthread_attr_setstacksize(pthread_attr_t *attr, size_t stacksize);",
    "pthread_barrier_destroy": "int pthread_barrier_destroy(pthread_barrier_t *barrier);",
    "pthread_barrier_init": "int pthread_barrier_init(pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned count);",
    "pthread_barrier_wait": "int pthread_barrier_wait(pthread_barrier_t *barrier);",
    "pthread_barrierattr_destroy": "int pthread_barrierattr_destroy(pthread_barrierattr_t *attr);",
    "pthread_barrierattr_getpshared": "int pthread_barrierattr_getpshared(const pthread_barrierattr_t *attr, int *pshared);",
    "pthread_barrierattr_init": "int pthread_barrierattr_init(pthread_barrierattr_t *attr);",
    "pthread_barrierattr_setpshared": "int pthread_barrierattr_setpshared(pthread_barrierattr_t *attr, int pshared);",
    "pthread_cancel": "int pthread_cancel(pthread_t thread);",
    "pthread_cleanup_pop": "void pthread_cleanup_pop(int execute);",
    "pthread_cleanup_push": "void pthread_cleanup_push(void (*routine)(void *), void *arg);",
    "pthread_cond_broadcast": "int pthread_cond_broadcast(pthread_cond_t *cond);",
    "pthread_cond_destroy": "int pthread_cond_destroy(pthread_cond_t *cond);",
    "pthread_cond_init": "int pthread_cond_init(pthread_cond_t *cond, const pthread_condattr_t *attr);",
    "pthread_cond_signal": "int pthread_cond_signal(pthread_cond_t *cond);",
    "pthread_cond_timedwait": "int pthread_cond_timedwait(pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime);",
    "pthread_cond_wait": "int pthread_cond_wait(pthread_cond_t *cond, pthread_mutex_t *mutex);",
    "pthread_condattr_destroy": "int pthread_condattr_destroy(pthread_condattr_t *attr);",
    "pthread_condattr_getclock": "int pthread_condattr_getclock(const pthread_condattr_t *attr, clockid_t *clock_id);",
    "pthread_condattr_getpshared": "int pthread_condattr_getpshared(const pthread_condattr_t *attr, int *pshared);",
    "pthread_condattr_init": "int pthread_condattr_init(pthread_condattr_t *attr);",
    "pthread_condattr_setclock": "int pthread_condattr_setclock(pthread_condattr_t *attr, clockid_t clock_id);",
    "pthread_condattr_setpshared": "int pthread_condattr_setpshared(pthread_condattr_t *attr, int pshared);",
    "pthread_create": "int pthread_create(pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);",
    "pthread_detach": "int pthread_detach(pthread_t thread);",
    "pthread_equal": "int pthread_equal(pthread_t t1, pthread_t t2);",
    "pthread_exit": "void pthread_exit(void *value_ptr);",
    "pthread_getconcurrency": "int pthread_getconcurrency(void);",
    "pthread_getcpuclockid": "int pthread_getcpuclockid(pthread_t thread_id, clockid_t *clock_id);",
    "pthread_getschedparam": "int pthread_getschedparam(pthread_t thread, int *policy, struct sched_param *param);",
    "pthread_getspecific": "void *pthread_getspecific(pthread_key_t key);",
    "pthread_join": "int pthread_join(pthread_t thread, void **value_ptr);",
    "pthread_key_create": "int pthread_key_create(pthread_key_t *key, void (*destructor)(void *));",
    "pthread_key_delete": "int pthread_key_delete(pthread_key_t key);",
    "pthread_mutex_destroy": "int pthread_mutex_destroy(pthread_mutex_t *mutex);",
    "pthread_mutex_init": "int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *attr);",
    "pthread_mutex_lock": "int pthread_mutex_lock(pthread_mutex_t *mutex);",
    "pthread_mutex_timedlock": "int pthread_mutex_timedlock(pthread_mutex_t *mutex, const struct timespec *abstime);",
    "pthread_mutex_trylock": "int pthread_mutex_trylock(pthread_mutex_t *mutex);",
    "pthread_mutex_unlock": "int pthread_mutex_unlock(pthread_mutex_t *mutex);",
    "pthread_mutexattr_destroy": "int pthread_mutexattr_destroy(pthread_mutexattr_t *attr);",
    "pthread_mutexattr_getprioceiling": "int pthread_mutexattr_getprioceiling(const pthread_mutexattr_t *attr, int *prioceiling);",
    "pthread_mutexattr_getprotocol": "int pthread_mutexattr_getprotocol(const pthread_mutexattr_t *attr, int *protocol);",
    "pthread_mutexattr_getpshared": "int pthread_mutexattr_getpshared(const pthread_mutexattr_t *attr, int *pshared);",
    "pthread_mutexattr_gettype": "int pthread_mutexattr_gettype(const pthread_mutexattr_t *attr, int *type);",
    "pthread_mutexattr_init": "int pthread_mutexattr_init(pthread_mutexattr_t *attr);",
    "pthread_mutexattr_setprioceiling": "int pthread_mutexattr_setprioceiling(pthread_mutexattr_t *attr, int prioceiling);",
    "pthread_mutexattr_setprotocol": "int pthread_mutexattr_setprotocol(pthread_mutexattr_t *attr, int protocol);",
    "pthread_mutexattr_setpshared": "int pthread_mutexattr_setpshared(pthread_mutexattr_t *attr, int pshared);",
    "pthread_mutexattr_settype": "int pthread_mutexattr_settype(pthread_mutexattr_t *attr, int type);",
    "pthread_once": "int pthread_once(pthread_once_t *once_control, void (*init_routine)(void));",
    "pthread_rwlock_destroy": "int pthread_rwlock_destroy(pthread_rwlock_t *rwlock);",
    "pthread_rwlock_init": "int pthread_rwlock_init(pthread_rwlock_t *rwlock, const pthread_rwlockattr_t *attr);",
    "pthread_rwlock_rdlock": "int pthread_rwlock_rdlock(pthread_rwlock_t *rwlock);",
    "pthread_rwlock_timedrdlock": "int pthread_rwlock_timedrdlock(pthread_rwlock_t *rwlock, const struct timespec *abstime);",
    "pthread_rwlock_timedwrlock": "int pthread_rwlock_timedwrlock(pthread_rwlock_t *rwlock, const struct timespec *abstime);",
    "pthread_rwlock_tryrdlock": "int pthread_rwlock_tryrdlock(pthread_rwlock_t *rwlock);",
    "pthread_rwlock_trywrlock": "int pthread_rwlock_trywrlock(pthread_rwlock_t *rwlock);",
    "pthread_rwlock_unlock": "int pthread_rwlock_unlock(pthread_rwlock_t *rwlock);",
    "pthread_rwlock_wrlock": "int pthread_rwlock_wrlock(pthread_rwlock_t *rwlock);",
    "pthread_rwlockattr_destroy": "int pthread_rwlockattr_destroy(pthread_rwlockattr_t *attr);",
    "pthread_rwlockattr_getpshared": "int pthread_rwlockattr_getpshared(const pthread_rwlockattr_t *attr, int *pshared);",
    "pthread_rwlockattr_init": "int pthread_rwlockattr_init(pthread_rwlockattr_t *attr);",
    "pthread_rwlockattr_setpshared": "int pthread_rwlockattr_setpshared(pthread_rwlockattr_t *attr, int pshared);",
    "pthread_self": "pthread_t pthread_self(void);",
    "pthread_setcancelstate": "int pthread_setcancelstate(int state, int *oldstate);",
    "pthread_setcanceltype": "int pthread_setcanceltype(int type, int *oldtype);",
    "pthread_setconcurrency": "int pthread_setconcurrency(int new_level);",
    "pthread_setschedparam": "int pthread_setschedparam(pthread_t thread, int policy, const struct sched_param *param);",
    "pthread_setschedprio": "int pthread_setschedprio(pthread_t thread, int prio);",
    "pthread_setspecific": "int pthread_setspecific(pthread_key_t key, const void *value);",
    "pthread_sigmask": "int pthread_sigmask(int how, const sigset_t *set, sigset_t *oset);",
    "pthread_spin_destroy": "int pthread_spin_destroy(pthread_spinlock_t *lock);",
    "pthread_spin_init": "int pthread_spin_init(pthread_spinlock_t *lock, int pshared);",
    "pthread_spin_lock": "int pthread_spin_lock(pthread_spinlock_t *lock);",
    "pthread_spin_trylock": "int pthread_spin_trylock(pthread_spinlock_t *lock);",
    "pthread_spin_unlock": "int pthread_spin_unlock(pthread_spinlock_t *lock);",
    "pthread_testcancel": "void pthread_testcancel(void);",
    "sched_get_priority_max": "int sched_get_priority_max(int policy);",
    "sched_get_priority_min": "int sched_get_priority_min(int policy);",
    "sched_getparam": "int sched_getparam(pid_t pid, struct sched_param *param);",
    "sched_getscheduler": "int sched_getscheduler(pid_t pid);",
    "sched_rr_get_interval": "int sched_rr_get_interval(pid_t pid, struct timespec *interval);",
    "sched_setparam": "int sched_setparam(pid_t pid, const struct sched_param *param);",
    "sched_setscheduler": "int sched_setscheduler(pid_t pid, int policy, const struct sched_param *param);",
    "sched_yield": "int sched_yield(void);",
    "sem_close": "int sem_close(sem_t *sem);",
    "sem_destroy": "int sem_destroy(sem_t *sem);",
    "sem_getvalue": "int sem_getvalue(sem_t *sem, int *sval);",
    "sem_init": "int sem_init(sem_t *sem, int pshared, unsigned int value);",
    "sem_open": "sem_t *sem_open(const char *name, int oflag, ...);",
    "sem_post": "int sem_post(sem_t *sem);",
    "sem_timedwait": "int sem_timedwait(sem_t *sem, const struct timespec *abs_timeout);",
    "sem_trywait": "int sem_trywait(sem_t *sem);",
    "sem_unlink": "int sem_unlink(const char *name);",
    "sem_wait": "int sem_wait(sem_t *sem);"
}

import json

with open('mappings.json', 'r') as f:
    data = json.load(f)

for func in data['mappings']['functions']:
    name = func['posix']
    if name not in sigs:
        print(f"MISSING: {name}")
