if(DEFINED WEPOLL_SOURCE_DIR AND EXISTS "${WEPOLL_SOURCE_DIR}/wepoll.c")
    file(READ "${WEPOLL_SOURCE_DIR}/wepoll.c" CONTENT)
    string(REPLACE "typedef void* nt__fn_ptr_cast_t;" "typedef void (*nt__fn_ptr_cast_t)(void);" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct tree {" "struct tree {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct tree_node {" "struct tree_node {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct ts_tree_node {" "struct ts_tree_node {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct queue_node {" "struct queue_node {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct queue {" "struct queue {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct poll_group {" "struct poll_group {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct port_state {" "struct port_state {" CONTENT "${CONTENT}")
    string(REPLACE "typedef struct sock_state {" "struct sock_state {" CONTENT "${CONTENT}")
    string(REPLACE "} tree_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} tree_node_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} ts_tree_node_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} queue_node_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} queue_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} poll_group_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} port_state_t;" "};" CONTENT "${CONTENT}")
    string(REPLACE "} sock_state_t;" "};" CONTENT "${CONTENT}")
    file(WRITE "${WEPOLL_SOURCE_DIR}/wepoll.c" "${CONTENT}")
endif()
